[project]
name = "zenvin-flight-path-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "folium>=0.19.4",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "ruff>=0.9.6",
]
